use_frameworks!

source '/Users/Tian/.cocoapods/repos/TZYSpecs'

target 'JingDataPhoneScreen_Example' do
  pod 'JingDataPhoneScreen', :path => '../'

  target 'JingDataPhoneScreen_Tests' do
    inherit! :search_paths

    
  end
end
